### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by RodGal-2020** [melissavanbussel/theme-generator#1]
When launching the app locally with my API key I get the following error:

```
Error in `req_perform()`:
! HTTP 404 Not Found.
```

and a server error too when using the website. By all I have seen, it looks like the way the API works has changed in the last month, and the way the request is written no longer works properly. I have not used the API by myself before, or else I would propose a modification of the `chat_response` variable to include the changes.

**Comment by RodGal-2020** [comment]
Just watching here and there I found out that the changes in the "Free trial" of the OpenAI API might be the cause, something interesting, as I have just started that trial and I no longer have any real free requests :/ 

Could this be the cause of the error?

**Comment by melissavanbussel** [comment]
Hi @RodGal-2020, thanks for trying out the app and for submitting an issue. Sorry it took me so long to take a look at this...it's been a busy couple of months. Thanks for your patience 🙂 

I just tried the app from both the browser and from cloning the repo and running locally, and it does still seem to be working as expected for me. I'm guessing it's an API key issue, and if there were changes to the free trial version of the API then that might be the culprit, unfortunately 🙁 

Not sure if you had seen this video already that I created but it might be helpful for troubleshooting: [https://www.youtube.com/watch?v=WWbuV43cV9Q](https://www.youtube.com/watch?v=WWbuV43cV9Q)

**Comment by RodGal-2020** [comment]
Thank you for your answer :).

I followed the video you shared, but the results were the same. I guess it must be something related to the API. If something changes and I manage to make it work with the new version, I will post it here.
